AWSTemplateFormatVersion: '2010-09-09'
Description: ServerlessOps API Authnz

Parameters:
  UserPoolName:
    Type: String
    Description: Name of UserPool

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      UserPoolName: !Ref UserPoolName
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
