AWSTemplateFormatVersion: '2010-09-09'
Description: Create a Cognito Resource Server

Parameters:
  CognitoUserPoolId:
    Type: AWS::SSM::Parameter::Value<String>
    Description: The ID of the user pool to which the resource server belongs
    Default: /org/authnz/UserPoolId
  ApplicationName:
    Type: String
    Description: The name of the application
  ApplicationUrl:
    Type: String
    Description: The URL of the application
  ScopeEntity:
    Type: String
    Description: The name of the scope
  ReadScopeAvailable:
    Type: String
    Description: Whether the read scope is available
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
  WriteScopeAvailable:
    Type: String
    Description: Whether the write scope is available
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
  AdminScopeAvailable:
    Type: String
    Description: Whether the admin scope is available
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
  HealthScopeAvailable:
    Type: String
    Description: Whether the admin scope is available
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'

Conditions:
  HasReadScope: !Equals [!Ref ReadScopeAvailable, 'true']
  HasWriteScope: !Equals [!Ref WriteScopeAvailable, 'true']
  HasAdminScope: !Equals [!Ref AdminScopeAvailable, 'true']
  HasHealthScope: !Equals [!Ref HealthScopeAvailable, 'true']

Resources:
  CognitoResourceServer:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
      Name: !Ref ApplicationName
      Identifier: !Ref ApplicationUrl
      UserPoolId: !Ref CognitoUserPoolId
      Scopes:
        - Fn::If:
          - HasReadScope
          - ScopeName: !Sub '${ScopeEntity}.read'
            ScopeDescription: Read access
          - Ref: AWS::NoValue
        - Fn::If:
          - HasWriteScope
          - ScopeName: !Sub '${ScopeEntity}.write'
            ScopeDescription: Write access
          - Ref: AWS::NoValue
        - Fn::If:
          - HasAdminScope
          - ScopeName: !Sub '${ScopeEntity}.admin'
            ScopeDescription: Admin access
          - Ref: AWS::NoValue
        - Fn::If:
          - HasHealthScope
          - ScopeName: 'health.read'
            ScopeDescription: Health access
          - Ref: AWS::NoValue
